### ISSUE TITLE
OverflowError on handling long ebqrcode values

### ISSUE THREAD

**Issue by dcast78** [raspibo/eventman#53]
When try to register an attendant using long ebqrcode values es:

```
  http://localhost:5242/events/552590580025e836ebc92ed4/persons/?ebqrcode=411254200519698130001
  {"attended": true, "checkin_datetime": "2015-04-22T17:41:38Z"}
```

MongoDB return an overflow error on int field

```
  OverflowError: MongoDB can only handle up to 8-byte ints
```

**Comment by alberanid** [comment]
Fixed storing integers longer than 64 bits as strings.

I've also introduced some fixes in the web server so that the 'attends' trigger is called also when the person is selected using a query, and not a person_id.

Moreover, a minor bug prevented some information (like the ebqrcode) to be stored in the person's data in an event, importing persons.
This should be fixed, but it requires to start over with an empty database and then re-import everything.

So, from the `mongo` prompt:

``` javascript
>>> use eventman
>>> db.persons.drop()
>>> db.events.drop()
```
